### ISSUE TITLE
二进制文件无法读取配置文件

### ISSUE THREAD

**Issue by lianmeng0** [CharellKing/ela#3]
使用二进制程序运行命令./ela.linux.amd64 ./config.yml

**Comment by lianmeng0** [comment]
> 使用二进制程序运行命令./ela.linux.amd64 ./config.yml
![image](https://github.com/user-attachments/assets/31706374-4dc1-4983-972b-fa03db543473)
但是报错：{"error":"invalid character '\u003c' looking for beginning of value","file":"D:/code/ela/main.go:37","func":"main.main","level":"error","msg":"create task manager","time":"2024-07-31T16:45:57+08:00"}
说配置文件解析格式错误，请问是怎么回事？

**Comment by quzhaojing** [comment]
your configure file has invalid characters.

**Comment by quzhaojing** [comment]
maybe it has some chinese space characters.

**Comment by lianmeng0** [comment]
> 也许它有一些中文空格字符。

它并没有中文字符，因为在英文格式下手写的配置文件同样出现问题，配置如下：
elastics:
  es7:
    addresses:
      - "http://172.17.64.85:9200"
  es8:
    addresses:
      - "http://172.17.10.71:9200"
tasks:
  - name: task1
    source_es: es7
    target_es: es8
    index_pairs:
      -
        source_index: "weibo_user"
        target_index: "weibo_user"
    action: sync
    force: true
    scroll_size: 5000
    parallelism: 12

**Comment by quzhaojing** [comment]
can you upload your configure file, you can speak english

**Comment by lianmeng0** [comment]
```
elastics:
  es7:
    addresses:
      - "http://172.17.64.85:9200"
  es8:
    addresses:
      - "http://172.17.10.71:9200"
tasks:
  - name: task1
    source_es: es7
    target_es: es8
    index_pairs:
      -
        source_index: "weibo_user"
        target_index: "weibo_user"
    action: sync
    force: true
    scroll_size: 5000
    parallelism: 12
```
