### ISSUE TITLE
Linux es7.1.1同步es 8.5.3

### ISSUE THREAD

**Issue by houziyu** [CharellKing/ela#4]
```
[root@one-tech-dev-database-master-09-20 ~]# ./ela.linux.amd64 ./config.yml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x708cb8]

goroutine 1 [running]:
github.com/CharellKing/ela/utils.GetCtxKeyTaskAction({0x0?, 0x0?})
        D:/code/ela/utils/ctx.go:69 +0x18
github.com/CharellKing/ela/service.(*Task).Run(0xc000030bf0)
        D:/code/ela/service/task.go:67 +0x45
github.com/CharellKing/ela/service.(*TaskMgr).Run(0xc0000b4c00, {0x1a19710, 0x2964820})
        D:/code/ela/service/taskmgr.go:50 +0x192
main.main()
        D:/code/ela/main.go:40 +0x1bc
```

es7为单点，es8 为集群，从es7同步为trade_开头的所有索引数据。

```
[root@one-tech-dev-database-master-09-20 ~]# cat config.yml
elastics:             # elasticsearch clusters
  es7:
    addresses:
      - "http://192.168.9.20:9200"
    user: "elastic"
    password: "123123Cxx"

  es8:
    addresses:
      - "https://192.168.9.121:9200"
    user: "elastic"
    password: "123123Cxx"

tasks:  # tasks which is executed orderly.
  - name: task1 # task name
    source_es: es7  # source elasticsearch cluster name which is defined in elastics config
    target_es: es8  # target elasticsearch cluster name which is defined in elastics config
    index_pattern: "trade_.*" # index pattern which is used to filter index to sync, source index is same with target index.
    action: sync # index actions which can be assigned to 'sync', 'compare', 'sync_diff'. sync to insert data, compare to compare source index with target index, sync_diff to sync data between source index and target index.
    force: true       # force to cover the target index data with source index data and settings.
    scroll_size: 1000 # scroll size which is used to scroll data from source index.
    scroll_time: 10   # scroll time which is used to scroll data from source index, default is 10 minutes.
    parallelism: 12   # parallelism which is used to sync data in parallel index pairs.
```

**Comment by houziyu** [comment]
I tried again and there was still a mistake.


[root@one-tech-dev-database-master-09-20 ~]# ./ela.linux.amd64 ./config.yml
Worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
Stack trace: goroutine 22 [running]:
runtime/debug.Stack()
        D:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
github.com/alitto/pond.defaultPanicHandler({0x16cd5e0, 0x28d1360})
        C:/Users/chare/go/pkg/mod/github.com/alitto/pond@v1.9.1/pond.go:26 +0x25
github.com/alitto/pond.(*WorkerPool).executeTask.func1()
        C:/Users/chare/go/pkg/mod/github.com/alitto/pond@v1.9.1/pond.go:443 +0x4a
panic({0x16cd5e0?, 0x28d1360?})
        D:/Program Files/Go/src/runtime/panic.go:770 +0x132
github.com/CharellKing/ela/pkg/es.(*V8).IndexExisted(0xc00014d3b0, {0xc0000fe920, 0x1c})
        D:/code/ela/pkg/es/es8.go:298 +0xb9
github.com/CharellKing/ela/service.(*Migrator).CopyIndexSettings(0xc0000b0de0, 0x1)
        D:/code/ela/service/migrator.go:94 +0x37
github.com/CharellKing/ela/service.(*Migrator).Sync(0xc0000b0de0, 0x0?)
        D:/code/ela/service/migrator.go:203 +0x1c
github.com/CharellKing/ela/service.(*BulkMigrator).Sync.func1(0xc0000b0de0)
        D:/code/ela/service/bulkmigrator.go:231 +0x25
github.com/CharellKing/ela/service.(*BulkMigrator).parallelRun.func1()
        D:/code/ela/service/bulkmigrator.go:329 +0x1b
github.com/alitto/pond.(*WorkerPool).executeTask(0xc0000d6180, 0x0?, 0x0?)
        C:/Users/chare/go/pkg/mod/github.com/alitto/pond@v1.9.1/pond.go:460 +0x6c
github.com/alitto/pond.worker({0x1a19780, 0xc0000f4820}, 0xc0000d6210, 0x0?, 0xc0000b0d80, 0xc0000975f0, 0xc0000d6220)
        C:/Users/chare/go/pkg/mod/github.com/alitto/pond@v1.9.1/worker.go:13 +0x6e
created by github.com/alitto/pond.(*WorkerPool).maybeStartWorker in goroutine 1
        C:/Users/chare/go/pkg/mod/github.com/alitto/pond@v1.9.1/pond.go:429 +0x145

{"file":"D:/code/ela/service/taskmgr.go:54","func":"github.com/CharellKing/ela/service.(*TaskMgr).Run","level":"info","msg":"task done","sourceEsSource":"7.1.1","targetEsTarget":"8.5.3","taskAction":"sync","taskId":"a22acab3-22cb-46e0-a0db-e1732f6e4cd0","taskName":"task1","time":"2024-08-12T10:16:17+08:00"}
```
[root@one-tech-dev-database-master-09-20 ~]# cat config.yml
elastics:
  es7:
    addresses:
      - "http://192.168.9.20:9200"
    user: "elastic"
    password: "123123Cxx"
  es8:
    addresses:
      - "https://192.168.9.121:9200"
    user: "elastic"
    password: "123123Cxx"

tasks:
  - name: task1
    source_es: es7
    target_es: es8
    index_pairs:
      -
        source_index: "trade_demand_original_demand"
        target_index: "trade_demand_original_demand"
    action: sync
    force: true
    scroll_size: 5000
    parallelism: 12
[root@one-tech-dev-database-master-09-20 ~]#           
```
